package com.salesforce.framework.enums;

public enum OpportunityStages
{
   PROSPECTING, QUALIFICATION, NEEDS_ANALYSIS, VALUE_PROPOSITION, ID_DECISION_MAKERS,
   PERCEPTION_ANALYSIS, PROPOSAL_PRICE_QUOTE, NEGOTIATION_REVIEW, CLOSED_WON, CLOSED_LOST
}
